// services/vaccinationAutoScheduler.js
import { doc, setDoc, collection, query, where, getDocs, getDoc, orderBy, limit, updateDoc, addDoc } from 'firebase/firestore'
import { db } from '@shared/firebase'
import { generateVaccinationAppointments, updatePetVaccinationProgress } from './vaccinationSeriesService'
import { createNotification } from './notificationService'

/**
 * Automatically schedule next vaccination appointments for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @param {Object} user - User object (owner)
 * @returns {Promise<Array>} Array of created appointment suggestions
 */
export async function autoScheduleVaccinations(pet, existingVaccinations = [], user = null) {
  try {
    console.log('🔄 Starting auto-scheduling for pet:', pet.name, 'with data:', {
      species: pet.species,
      birthDate: pet.birthDate,
      ageWeeks: pet.ageWeeks,
      ageMonths: pet.ageMonths,
      ageYears: pet.ageYears
    })
    
    // Generate vaccination appointment suggestions
    const appointmentSuggestions = generateVaccinationAppointments(pet, existingVaccinations)
    console.log('📅 Generated appointment suggestions:', appointmentSuggestions.length, appointmentSuggestions)
    
    if (appointmentSuggestions.length === 0) {
      console.log(`No vaccination appointments needed for ${pet.name}`)
      return []
    }
    
    // Find available vaccination services
    const availableServices = await findVaccinationServices()
    console.log('🔍 Found available vaccination services:', availableServices.length, availableServices.map(s => s.name))
    
    // Create appointment suggestions with service mapping
    const scheduledAppointments = []
    
    for (const suggestion of appointmentSuggestions) {
      // Find matching service
      const matchingService = findMatchingService(suggestion.serviceName, availableServices)
      console.log(`🔍 Looking for service matching "${suggestion.serviceName}":`, matchingService ? matchingService.name : 'No match')
      
      if (matchingService) {
        const appointmentData = {
          id: `vacc_suggest_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          type: 'vaccination_suggestion',
          status: 'suggestion',
          petId: pet.id,
          petName: pet.name,
          serviceId: matchingService.id,
          serviceName: matchingService.name,
          suggestedDate: suggestion.suggestedDate,
          priority: suggestion.priority,
          series: suggestion.series,
          dose: suggestion.dose,
          totalDoses: suggestion.totalDoses,
          isCore: suggestion.isCore,
          description: suggestion.description,
          estimatedDuration: suggestion.estimatedDuration,
          notes: suggestion.notes,
          createdAt: new Date(),
          updatedAt: new Date(),
          isAutoGenerated: true,
          source: 'vaccination_series'
        }
        
        // Save to Firestore
        await saveVaccinationSuggestion(appointmentData)
        scheduledAppointments.push(appointmentData)
        
        console.log(`✅ Created vaccination suggestion for ${pet.name}: ${suggestion.serviceName}`)
      } else {
        console.log(`❌ No matching service found for ${suggestion.serviceName}`)
      }
    }
    
    console.log(`🎯 Auto-scheduling completed for ${pet.name}: ${scheduledAppointments.length} suggestions created`)
    return scheduledAppointments
  } catch (error) {
    console.error('Error auto-scheduling vaccinations:', error)
    throw new Error('Failed to auto-schedule vaccinations')
  }
}

/**
 * Find vaccination service by name
 * @param {string} vaccineName - Name of the vaccine
 * @returns {Promise<Object|null>} Vaccination service or null
 */
async function findVaccinationServiceByName(vaccineName) {
  try {
    const servicesRef = collection(db, 'services')
    const q = query(
      servicesRef,
      where('isVaccination', '==', true),
      where('archived', '==', false)
    )
    
    const snapshot = await getDocs(q)
    const services = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }))
    
    console.log('🔍 Found vaccination services:', services.map(s => ({
      id: s.id,
      name: s.name,
      vaccineType: s.vaccineType,
      isVaccination: s.isVaccination
    })))
    
    // First try exact match
    let matchingService = services.find(service => 
      service.name.toLowerCase() === vaccineName.toLowerCase()
    )
    
    if (matchingService) {
      console.log('✅ Exact match found:', matchingService.name)
      return matchingService
    }
    
    // Try partial match by name
    matchingService = services.find(service => 
      service.name.toLowerCase().includes(vaccineName.toLowerCase()) ||
      vaccineName.toLowerCase().includes(service.name.toLowerCase())
    )
    
    if (matchingService) {
      console.log('✅ Partial name match found:', matchingService.name)
      return matchingService
    }
    
    // Try matching by vaccineType
    matchingService = services.find(service => 
      service.vaccineType && 
      service.vaccineType.toLowerCase() === vaccineName.toLowerCase()
    )
    
    if (matchingService) {
      console.log('✅ VaccineType match found:', matchingService.name)
      return matchingService
    }
    
    // Try partial match by vaccineType
    matchingService = services.find(service => 
      service.vaccineType && 
      (service.vaccineType.toLowerCase().includes(vaccineName.toLowerCase()) ||
       vaccineName.toLowerCase().includes(service.vaccineType.toLowerCase()))
    )
    
    if (matchingService) {
      console.log('✅ Partial vaccineType match found:', matchingService.name)
      return matchingService
    }
    
    console.log('❌ No matching vaccination service found for:', vaccineName)
    return null
  } catch (error) {
    console.error('Error finding vaccination service by name:', error)
    return null
  }
}

/**
 * Find available vaccination services in the system
 * @returns {Promise<Array>} Array of vaccination services
 */
async function findVaccinationServices() {
  try {
    const servicesRef = collection(db, 'services')
    const q = query(
      servicesRef,
      where('isVaccination', '==', true),
      where('archived', '==', false)
    )
    
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error finding vaccination services:', error)
    return []
  }
}

/**
 * Find the best matching service for a vaccination suggestion
 * @param {string} vaccineName - Name of the vaccine
 * @param {Array} availableServices - Array of available services
 * @returns {Object|null} Matching service or null
 */
function findMatchingService(vaccineName, availableServices) {
  if (!availableServices || availableServices.length === 0) {
    return null
  }
  
  const vaccineNameLower = vaccineName.toLowerCase()
  
  // Try exact match first
  let exactMatch = availableServices.find(service => 
    service.name.toLowerCase() === vaccineNameLower
  )
  
  if (exactMatch) return exactMatch
  
  // Try partial matches
  const partialMatches = availableServices.filter(service => {
    const serviceNameLower = service.name.toLowerCase()
    
    // Check if service name contains key vaccine terms
    const keyTerms = vaccineNameLower.split(' ')
    return keyTerms.some(term => 
      term.length > 2 && serviceNameLower.includes(term)
    )
  })
  
  if (partialMatches.length > 0) {
    // Return the best partial match (prioritize core vaccines)
    return partialMatches.sort((a, b) => {
      if (a.name.toLowerCase().includes('core') && !b.name.toLowerCase().includes('core')) return -1
      if (!a.name.toLowerCase().includes('core') && b.name.toLowerCase().includes('core')) return 1
      return 0
    })[0]
  }
  
  // Fallback to generic vaccination service
  return availableServices.find(service => 
    service.name.toLowerCase().includes('vaccination') ||
    service.name.toLowerCase().includes('vaccine')
  ) || availableServices[0]
}

/**
 * Save vaccination suggestion to Firestore
 * @param {Object} appointmentData - Appointment suggestion data
 * @returns {Promise} Save result
 */
async function saveVaccinationSuggestion(appointmentData) {
  try {
    const suggestionRef = doc(db, 'vaccinationSuggestions', appointmentData.id)
    await setDoc(suggestionRef, appointmentData)
    return { success: true, id: appointmentData.id }
  } catch (error) {
    console.error('Error saving vaccination suggestion:', error)
    throw new Error('Failed to save vaccination suggestion')
  }
}

/**
 * Get all vaccination suggestions for a pet
 * @param {string} petId - Pet ID
 * @returns {Promise<Array>} Array of vaccination suggestions
 */
export async function getVaccinationSuggestions(petId) {
  try {
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const q = query(
      suggestionsRef,
      where('petId', '==', petId),
      where('status', '==', 'suggestion'),
      orderBy('suggestedDate', 'asc')
    )
    
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error fetching vaccination suggestions:', error)
    return []
  }
}

/**
 * Get all vaccination suggestions for a user
 * @param {string} userId - User ID
 * @returns {Promise<Array>} Array of vaccination suggestions
 */
export async function getUserVaccinationSuggestions(userId) {
  try {
    // First get user's pets
    const petsRef = collection(db, 'pets')
    const petsQuery = query(petsRef, where('userId', '==', userId))
    const petsSnapshot = await getDocs(petsQuery)
    
    if (petsSnapshot.empty) return []
    
    const petIds = petsSnapshot.docs.map(doc => doc.id)
    
    // Get suggestions for all user's pets
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const suggestionsQuery = query(
      suggestionsRef,
      where('petId', 'in', petIds),
      where('status', '==', 'suggestion'),
      orderBy('suggestedDate', 'asc')
    )
    
    const suggestionsSnapshot = await getDocs(suggestionsQuery)
    return suggestionsSnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error('Error fetching user vaccination suggestions:', error)
    return []
  }
}

/**
 * Convert vaccination suggestion to actual appointment
 * @param {string} suggestionId - Vaccination suggestion ID
 * @param {Object} appointmentData - Additional appointment data
 * @returns {Promise<Object>} Created appointment
 */
export async function convertSuggestionToAppointment(suggestionId, appointmentData = {}) {
  try {
    // Get the suggestion
    const suggestionsRef = collection(db, 'vaccinationSuggestions')
    const suggestionDoc = await getDocs(query(suggestionsRef, where('id', '==', suggestionId)))
    
    if (suggestionDoc.empty) {
      throw new Error('Vaccination suggestion not found')
    }
    
    const suggestion = suggestionDoc.docs[0].data()
    
    // Create appointment data
    const newAppointment = {
      services: [suggestion.serviceId],
      serviceNames: [suggestion.serviceName],
      duration: suggestion.estimatedDuration || 30,
      petIds: [suggestion.petId],
      petNames: [suggestion.petName],
      doctorId: appointmentData.doctorId || null,
      doctorName: appointmentData.doctorName || null,
      date: appointmentData.date || suggestion.suggestedDate,
      time: appointmentData.time || null,
      userId: appointmentData.userId || suggestion.userId,
      status: appointmentData.status || 'pending',
      isVaccination: true,
      vaccinationSeries: suggestion.series,
      vaccinationDose: suggestion.dose,
      vaccinationTotalDoses: suggestion.totalDoses,
      isCore: suggestion.isCore,
      notes: suggestion.notes,
      createdAt: new Date(),
      updatedAt: new Date(),
      source: 'vaccination_auto_schedule',
      originalSuggestionId: suggestionId,
      // Add auto-approval metadata if provided
      ...(appointmentData.isAutoApproved && {
        isAutoApproved: appointmentData.isAutoApproved,
        autoApprovedAt: appointmentData.autoApprovedAt,
        autoApprovedReason: appointmentData.autoApprovedReason
      })
    }
    
    // Save to appointments collection
    const appointmentRef = doc(collection(db, 'appointments'))
    await setDoc(appointmentRef, {
      ...newAppointment,
      id: appointmentRef.id
    })
    
    // Update suggestion status
    await updateVaccinationSuggestionStatus(suggestionId, 'converted')
    
    return { ...newAppointment, id: appointmentRef.id }
  } catch (error) {
    console.error('Error converting suggestion to appointment:', error)
    throw new Error('Failed to convert suggestion to appointment')
  }
}

/**
 * Update vaccination suggestion status
 * @param {string} suggestionId - Suggestion ID
 * @param {string} status - New status
 * @returns {Promise} Update result
 */
async function updateVaccinationSuggestionStatus(suggestionId, status) {
  try {
    const suggestionRef = doc(db, 'vaccinationSuggestions', suggestionId)
    await updateDoc(suggestionRef, {
      status: status,
      updatedAt: new Date()
    })
    return { success: true }
  } catch (error) {
    console.error('Error updating vaccination suggestion status:', error)
    throw new Error('Failed to update suggestion status')
  }
}

/**
 * Calculate next vaccination date using boosterSchedule configuration
 * @param {Object} vaccinationService - Vaccination service configuration
 * @param {Object} boosterLimitCheck - Booster limit check result
 * @param {Date} baseDate - Base date to calculate from
 * @returns {Date} Next vaccination date
 */
export function calculateNextVaccinationDateFromBoosterSchedule(vaccinationService, boosterLimitCheck, baseDate = new Date()) {
  try {
    console.log('🔍 Calculating next vaccination date from booster schedule:', {
      boosterSchedule: vaccinationService.boosterSchedule,
      nextBoosterNumber: boosterLimitCheck.nextBoosterNumber,
      baseDate: baseDate
    })
    
    // If no booster schedule is configured, use default nextDoseIn
    if (!vaccinationService.boosterSchedule || Object.keys(vaccinationService.boosterSchedule).length === 0) {
      console.log('ℹ️ No booster schedule configured, using default nextDoseIn')
      return calculateNextVaccinationDateFromService(vaccinationService, baseDate)
    }
    
    const boosterNumber = boosterLimitCheck.nextBoosterNumber
    const boosterSchedule = vaccinationService.boosterSchedule
    
    // Look for specific booster schedule entry
    let scheduleEntry = null
    
    // Try to find exact booster number match
    if (boosterSchedule[boosterNumber]) {
      scheduleEntry = boosterSchedule[boosterNumber]
      console.log(`✅ Found specific schedule for booster ${boosterNumber}:`, scheduleEntry)
    }
    // Try to find by description matching
    else {
      const boosterNumberStr = boosterNumber.toString()
      for (const [key, value] of Object.entries(boosterSchedule)) {
        if (value.description && value.description.toLowerCase().includes(boosterNumberStr)) {
          scheduleEntry = value
          console.log(`✅ Found schedule by description for booster ${boosterNumber}:`, scheduleEntry)
          break
        }
      }
    }
    
    // If no specific schedule found, use the first available schedule
    if (!scheduleEntry && Object.keys(boosterSchedule).length > 0) {
      const firstKey = Object.keys(boosterSchedule)[0]
      scheduleEntry = boosterSchedule[firstKey]
      console.log(`⚠️ No specific schedule for booster ${boosterNumber}, using first available:`, scheduleEntry)
    }
    
    // If still no schedule found, fall back to default
    if (!scheduleEntry) {
      console.log('⚠️ No booster schedule entry found, using default nextDoseIn')
      return calculateNextVaccinationDateFromService(vaccinationService, baseDate)
    }
    
    // Calculate next date based on schedule entry
    const nextDate = new Date(baseDate)
    const interval = scheduleEntry.interval || vaccinationService.nextDoseIn || 14
    const unit = scheduleEntry.unit || vaccinationService.nextDoseUnit || 'days'
    
    console.log('🔍 Using booster schedule:', {
      interval,
      unit,
      description: scheduleEntry.description
    })
    
    // Add the interval based on the unit
    switch (unit.toLowerCase()) {
      case 'days':
        nextDate.setDate(nextDate.getDate() + interval)
        break
      case 'weeks':
        nextDate.setDate(nextDate.getDate() + (interval * 7))
        break
      case 'months':
        nextDate.setMonth(nextDate.getMonth() + interval)
        break
      case 'years':
        nextDate.setFullYear(nextDate.getFullYear() + interval)
        break
      default:
        console.log('⚠️ Unknown unit, defaulting to days')
        nextDate.setDate(nextDate.getDate() + interval)
    }
    
    console.log('✅ Calculated next vaccination date from booster schedule:', nextDate)
    return nextDate
    
  } catch (error) {
    console.error('Error calculating next vaccination date from booster schedule:', error)
    // Fall back to default calculation
    return calculateNextVaccinationDateFromService(vaccinationService, baseDate)
  }
}

/**
 * Check if booster limits allow scheduling another vaccination
 * @param {Object} completedVaccination - Completed vaccination record
 * @param {Object} pet - Pet object
 * @param {Object} vaccinationService - Vaccination service configuration
 * @returns {Promise<Object>} Object with shouldSchedule boolean and details
 */
export async function checkBoosterLimits(completedVaccination, pet, vaccinationService) {
  try {
    console.log('🔍 Checking booster limits for:', {
      vaccineName: completedVaccination.name,
      petName: pet.name,
      totalBoosters: vaccinationService.totalBoosters
    })
    
    // Get all existing vaccination records for this pet
    const petVaccinationsRef = collection(db, 'pets', pet.id, 'vaccinations')
    const vaccinationsSnapshot = await getDocs(petVaccinationsRef)
    
    const existingVaccinations = []
    vaccinationsSnapshot.forEach(doc => {
      const data = doc.data()
      if (data.completed) {
        existingVaccinations.push({ id: doc.id, ...data })
      }
    })
    
    console.log('🔍 Found existing vaccinations:', existingVaccinations.length)
    
    // Count boosters for this specific vaccine
    const vaccineName = completedVaccination.name.toLowerCase()
    const boosterVaccinations = existingVaccinations.filter(vaccination => {
      const vaccinationName = vaccination.name.toLowerCase()
      // Check if it's a booster for the same vaccine
      return vaccinationName.includes('booster') && 
             vaccinationName.includes(vaccineName.split(' ')[0]) // Match base vaccine name
    })
    
    console.log('🔍 Found booster vaccinations for this vaccine:', boosterVaccinations.length)
    console.log('🔍 Booster vaccinations:', boosterVaccinations.map(v => ({
      name: v.name,
      date: v.date,
      completed: v.completed
    })))
    
    const currentBoosters = boosterVaccinations.length
    const totalBoosters = vaccinationService.totalBoosters || 1
    const nextBoosterNumber = currentBoosters + 1
    
    // Check if we've reached the limit
    if (currentBoosters >= totalBoosters) {
      return {
        shouldSchedule: false,
        reason: `Booster limit reached (${currentBoosters}/${totalBoosters})`,
        currentBoosters,
        totalBoosters,
        nextBoosterNumber
      }
    }
    
    // Check if this is the first vaccination (not a booster)
    const isFirstVaccination = !completedVaccination.name.toLowerCase().includes('booster')
    if (isFirstVaccination && currentBoosters === 0) {
      // First vaccination - check if boosters are allowed
      if (totalBoosters > 0) {
        return {
          shouldSchedule: true,
          reason: 'First vaccination, boosters allowed',
          currentBoosters,
          totalBoosters,
          nextBoosterNumber: 1
        }
      } else {
        return {
          shouldSchedule: false,
          reason: 'No boosters configured for this vaccine',
          currentBoosters,
          totalBoosters,
          nextBoosterNumber
        }
      }
    }
    
    // This is a booster vaccination - check if we can schedule another
    if (currentBoosters < totalBoosters) {
      return {
        shouldSchedule: true,
        reason: `Booster ${nextBoosterNumber} of ${totalBoosters} allowed`,
        currentBoosters,
        totalBoosters,
        nextBoosterNumber
      }
    }
    
    return {
      shouldSchedule: false,
      reason: 'Unknown booster limit condition',
      currentBoosters,
      totalBoosters,
      nextBoosterNumber
    }
    
  } catch (error) {
    console.error('Error checking booster limits:', error)
    // Default to allowing scheduling if there's an error
    return {
      shouldSchedule: true,
      reason: 'Error checking limits, defaulting to allow',
      currentBoosters: 0,
      totalBoosters: vaccinationService.totalBoosters || 1,
      nextBoosterNumber: 1,
      error: error.message
    }
  }
}

/**
 * Process completed vaccination and auto-schedule next dose
 * @param {Object} completedVaccination - Completed vaccination record
 * @param {Object} pet - Pet object
 * @param {Object} user - User object
 * @returns {Promise<Array>} Array of new appointment suggestions
 */
export async function processCompletedVaccination(completedVaccination, pet, user) {
  try {
    console.log('🩺 Processing completed vaccination for autoscheduling...', { 
      pet: pet.name, 
      vaccine: completedVaccination.name,
      petData: {
        id: pet.id,
        species: pet.species,
        birthDate: pet.birthDate,
        ageWeeks: pet.ageWeeks,
        ageMonths: pet.ageMonths,
        ageYears: pet.ageYears
      }
    })
    
    // Update pet's vaccination progress
    await updatePetVaccinationProgress(pet.id, completedVaccination)
    console.log('✅ Updated pet vaccination progress')
    
    // Directly create next vaccination appointment based on completed vaccination
    const nextVaccinationAppointment = await createNextVaccinationAppointment(completedVaccination, pet, user)
    
    if (nextVaccinationAppointment) {
      console.log('✅ Created next vaccination appointment:', nextVaccinationAppointment.id)
      
      // Send notification to user about the scheduled vaccination
      await sendVaccinationAppointmentNotification(nextVaccinationAppointment, pet, user)
      console.log('✅ Sent vaccination appointment notification')
      
      return [nextVaccinationAppointment]
    } else {
      console.log('ℹ️ No next vaccination appointment needed at this time')
      return []
    }
    
  } catch (error) {
    console.error('Error processing completed vaccination:', error)
    throw new Error('Failed to process completed vaccination')
  }
}

/**
 * Get overdue vaccinations for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @returns {Array} Array of overdue vaccinations
 */
export function getOverdueVaccinations(pet, existingVaccinations = []) {
  const upcomingVaccinations = generateVaccinationAppointments(pet, existingVaccinations)
  const now = new Date()
  
  return upcomingVaccinations.filter(vaccination => {
    const dueDate = new Date(vaccination.suggestedDate)
    return dueDate < now
  })
}

/**
 * Get vaccination schedule summary for a pet
 * @param {Object} pet - Pet object
 * @param {Array} existingVaccinations - Array of existing vaccination records
 * @returns {Object} Vaccination schedule summary
 */
export function getVaccinationScheduleSummary(pet, existingVaccinations = []) {
  const upcomingVaccinations = generateVaccinationAppointments(pet, existingVaccinations)
  const overdueVaccinations = getOverdueVaccinations(pet, existingVaccinations)
  
  const completedVaccinations = existingVaccinations.filter(v => v.completed)
  const pendingVaccinations = upcomingVaccinations.filter(v => !v.completed)
  
  return {
    total: existingVaccinations.length + upcomingVaccinations.length,
    completed: completedVaccinations.length,
    pending: pendingVaccinations.length,
    overdue: overdueVaccinations.length,
    nextDue: upcomingVaccinations.length > 0 ? upcomingVaccinations[0] : null,
    series: upcomingVaccinations.length > 0 ? upcomingVaccinations[0].series : null,
    progress: existingVaccinations.length > 0 ? 
      Math.round((completedVaccinations.length / existingVaccinations.length) * 100) : 0
  }
}

/**
 * Create next vaccination appointment based on completed vaccination
 * @param {Object} completedVaccination - The completed vaccination record
 * @param {Object} pet - Pet object
 * @param {Object} user - User object
 * @returns {Promise<Object|null>} Created appointment or null if not needed
 */
export async function createNextVaccinationAppointment(completedVaccination, pet, user) {
  try {
    console.log('🔄 Creating next vaccination appointment for:', completedVaccination.name)
    
    // Try to get vaccination service from the completed vaccination record first
    let vaccinationService = null
    
    // First, check if we have vaccination service data stored in the vaccination record
    if (completedVaccination.vaccinationServiceData) {
      vaccinationService = completedVaccination.vaccinationServiceData
      console.log('✅ Found vaccination service data in vaccination record:', vaccinationService.name)
    }
    // If not found in vaccination record, try to get it from Firestore by serviceId
    else if (completedVaccination.serviceId) {
      try {
        const serviceRef = doc(db, 'services', completedVaccination.serviceId)
        const serviceDoc = await getDoc(serviceRef)
        if (serviceDoc.exists()) {
          vaccinationService = { id: serviceDoc.id, ...serviceDoc.data() }
          console.log('✅ Found vaccination service by ID:', vaccinationService.name)
        }
      } catch (error) {
        console.log('⚠️ Error fetching service by ID:', error)
      }
    }
    
    // If still not found, try to find by name
    if (!vaccinationService) {
      vaccinationService = await findVaccinationServiceByName(completedVaccination.name)
    }
    
    if (!vaccinationService) {
      console.log('❌ No vaccination service found for:', completedVaccination.name)
      console.log('🔍 Attempting to create appointment with default values...')
      
      // Create appointment with default values if service not found
      const defaultNextDate = new Date()
      defaultNextDate.setFullYear(defaultNextDate.getFullYear() + 1) // Default to 1 year
      
      // Get the original appointment time and duration from the completed vaccination
      const originalAppointmentTime = completedVaccination.appointmentTime || '1:00 PM - 2:00 PM' // Fallback
      const originalDuration = completedVaccination.appointmentDuration || 60 // Fallback to 60 minutes
      
      // Adjust default date to office hours
      const adjustedDefaultDate = await adjustDateToOfficeHours(defaultNextDate, user?.id || user?.userId, pet.id)
      
      // Get the vet ID from the completed vaccination - this should be the actual vet who completed the vaccination
      const vetId = completedVaccination.doctorId || completedVaccination.administeredBy || 'default_vet_id'
      const vetName = completedVaccination.doctorName || completedVaccination.administeredBy || 'Auto-Scheduled'
      
          console.log('👨‍⚕️ Using vet ID for fallback auto-scheduled appointment:', vetId)
    
    // 🔧 DEBUG: Log what we're receiving from the vaccination record
    console.log('🔍 Vaccination record data for fallback auto-scheduling:', {
      completedVaccinationDoctorId: completedVaccination.doctorId,
      completedVaccinationAdministeredBy: completedVaccination.administeredBy,
      completedVaccinationDoctorName: completedVaccination.doctorName,
      finalVetId: vetId,
      finalVetName: vetName
    })
    
    console.log('🕐 Using original appointment time:', originalAppointmentTime)
      console.log('⏱️ Using original appointment duration:', originalDuration)
      
      // Create booster service name
      const boosterServiceName = `${completedVaccination.name} - BOOSTER`
      
      const appointmentData = {
        userId: user?.id || user?.userId,
        petIds: [pet.id],
        petNames: [pet.name],
        doctorId: vetId, // Use the actual vet ID who completed the vaccination
        doctorName: vetName,
        serviceNames: [boosterServiceName], // Add "BOOSTER" to service name
        servicesIds: [completedVaccination.serviceId || 'unknown'],
        services: [completedVaccination.serviceId || 'unknown'], // Add services field to match user-created appointments
        date: adjustedDefaultDate,
        time: originalAppointmentTime, // Use the same time as original appointment
        duration: originalDuration, // Use the same duration as original appointment
        status: 'approved',
        isVaccination: true,
        isAutoScheduled: true,
        autoScheduledAt: new Date(),
        autoScheduledReason: 'Vaccination series continuation - BOOSTER (default schedule)',
        vaccinationSeries: 'Standard',
        vaccinationDose: 'booster',
        vaccinationTotalDoses: 1,
        isCore: completedVaccination.isCore || false,
        notes: `Auto-scheduled BOOSTER vaccination for ${completedVaccination.name} - This is a follow-up vaccination appointment.`,
        createdAt: new Date(),
        updatedAt: new Date(),
        source: 'vaccination_auto_schedule',
        previousVaccinationId: completedVaccination.id
      }
      
      // Save to appointments collection
      const appointmentRef = doc(collection(db, 'appointments'))
      await setDoc(appointmentRef, {
        ...appointmentData,
        id: appointmentRef.id
      })
      
      console.log('✅ Created next vaccination appointment with default values:', appointmentRef.id)
      return { ...appointmentData, id: appointmentRef.id }
    }
    
    console.log('🔍 Found vaccination service:', {
      name: vaccinationService.name,
      nextDoseIn: vaccinationService.nextDoseIn,
      nextDoseUnit: vaccinationService.nextDoseUnit,
      autoSchedule: vaccinationService.autoSchedule,
      seriesType: vaccinationService.seriesType,
      totalBoosters: vaccinationService.totalBoosters,
      vaccineType: vaccinationService.vaccineType
    })
    
    // Check if auto-scheduling is enabled for this service
    if (vaccinationService.autoSchedule !== true) {
      console.log('ℹ️ Auto-scheduling is disabled for this service')
      return null
    }
    
    // 🔧 NEW: Check booster limits before scheduling
    const boosterLimitCheck = await checkBoosterLimits(completedVaccination, pet, vaccinationService)
    if (!boosterLimitCheck.shouldSchedule) {
      console.log('ℹ️ Booster limit reached or exceeded:', boosterLimitCheck.reason)
      return null
    }
    
    console.log('✅ Booster limit check passed:', {
      currentBoosters: boosterLimitCheck.currentBoosters,
      totalBoosters: boosterLimitCheck.totalBoosters,
      nextBoosterNumber: boosterLimitCheck.nextBoosterNumber
    })
    
    // Calculate next vaccination date using booster schedule or service data
    const nextVaccinationDate = calculateNextVaccinationDateFromBoosterSchedule(vaccinationService, boosterLimitCheck, new Date())
    
    // Check if next vaccination is needed (not too far in the future)
    const maxFutureDate = new Date()
    maxFutureDate.setFullYear(maxFutureDate.getFullYear() + 2) // Max 2 years in future
    
    if (nextVaccinationDate > maxFutureDate) {
      console.log('ℹ️ Next vaccination date is too far in the future, skipping')
      return null
    }
    
    // Get the original appointment time and duration from the completed vaccination
    const originalAppointmentTime = completedVaccination.appointmentTime || '1:00 PM - 2:00 PM' // Fallback
    const originalDuration = completedVaccination.appointmentDuration || 60 // Fallback to 60 minutes
    
    // Get the vet ID from the completed vaccination - this should be the actual vet who completed the vaccination
    const vetId = completedVaccination.doctorId || completedVaccination.administeredBy || 'default_vet_id'
    const vetName = completedVaccination.doctorName || completedVaccination.administeredBy || 'Auto-Scheduled'
    
    console.log('👨‍⚕️ Using vet ID for auto-scheduled appointment:', vetId)
    
    // 🔧 DEBUG: Log what we're receiving from the vaccination record
    console.log('🔍 Vaccination record data for auto-scheduling:', {
      completedVaccinationDoctorId: completedVaccination.doctorId,
      completedVaccinationAdministeredBy: completedVaccination.administeredBy,
      completedVaccinationDoctorName: completedVaccination.doctorName,
      finalVetId: vetId,
      finalVetName: vetName
    })
    
    console.log('🕐 Using original appointment time:', originalAppointmentTime)
    console.log('⏱️ Using original appointment duration:', originalDuration)
    
    // Create booster service name with booster number
    const boosterNumber = boosterLimitCheck.nextBoosterNumber
    const boosterServiceName = `${vaccinationService.name} - BOOSTER ${boosterNumber}`
    
    const appointmentData = {
      userId: user?.id || user?.userId,
      petIds: [pet.id],
      petNames: [pet.name],
      doctorId: vetId, // Use the actual vet ID who completed the vaccination
      doctorName: vetName,
      serviceNames: [boosterServiceName], // Add "BOOSTER X" to service name
      servicesIds: [vaccinationService.id],
      services: [vaccinationService.id], // Add services field to match user-created appointments
      date: nextVaccinationDate,
      time: originalAppointmentTime, // Use the same time as original appointment
      duration: originalDuration, // Use the same duration as original appointment
      status: 'approved', // Auto-approved status as requested
      isVaccination: true,
      isAutoScheduled: true,
      autoScheduledAt: new Date(),
      autoScheduledReason: `Vaccination series continuation - BOOSTER ${boosterNumber} of ${boosterLimitCheck.totalBoosters}`,
      vaccinationSeries: vaccinationService.seriesType || 'Standard',
      vaccinationDose: `booster_${boosterNumber}`,
      vaccinationTotalDoses: vaccinationService.totalBoosters || 1,
      vaccinationCurrentDose: boosterNumber,
      isCore: completedVaccination.isCore || false,
      notes: `Auto-scheduled BOOSTER ${boosterNumber} vaccination for ${vaccinationService.name} - This is booster ${boosterNumber} of ${boosterLimitCheck.totalBoosters}.`,
      createdAt: new Date(),
      updatedAt: new Date(),
      source: 'vaccination_auto_schedule',
      previousVaccinationId: completedVaccination.id,
      vaccineType: vaccinationService.vaccineType,
      boosterLimitInfo: {
        currentBoosters: boosterLimitCheck.currentBoosters,
        totalBoosters: boosterLimitCheck.totalBoosters,
        nextBoosterNumber: boosterLimitCheck.nextBoosterNumber
      }
    }
    
    // Save to appointments collection
    const appointmentRef = doc(collection(db, 'appointments'))
    await setDoc(appointmentRef, {
      ...appointmentData,
      id: appointmentRef.id
    })
    
    console.log('✅ Created next vaccination appointment:', appointmentRef.id)
    
    return { ...appointmentData, id: appointmentRef.id }
  } catch (error) {
    console.error('Error creating next vaccination appointment:', error)
    return null
  }
}

/**
 * Test function to verify auto-scheduling is working
 * This can be called from browser console for debugging
 */
export async function testVaccinationAutoScheduling() {
  try {
    console.log('🧪 Testing vaccination auto-scheduling with office hours...')
    
    // Create a mock vaccination record
    const mockVaccination = {
      id: 'test_vacc_123',
      name: 'Rabies Vaccine',
      serviceId: 'test_service_id',
      doctorId: 'test_vet_id', // Add vet ID
      doctorName: 'Test Vet',
      appointmentTime: '1:00 PM - 2:10 PM', // Add appointment time
      appointmentDuration: 70, // Add appointment duration (70 minutes)
      vaccinationServiceData: {
        id: 'test_service_id',
        name: 'Rabies Vaccine',
        nextDoseIn: 14,
        nextDoseUnit: 'days',
        autoSchedule: true,
        seriesType: 'single',
        totalBoosters: 1,
        vaccineType: 'Rabies'
      },
      administeredBy: 'Test Vet',
      isCore: true
    }
    
    const mockPet = {
      id: 'test_pet_id',
      name: 'Test Pet',
      species: 'Dog'
    }
    
    const mockUser = {
      id: 'test_user_id',
      firstName: 'Test',
      lastName: 'User'
    }
    
    console.log('🧪 Mock data created:', { mockVaccination, mockPet, mockUser })
    
    // Test the auto-scheduling
    const result = await processCompletedVaccination(mockVaccination, mockPet, mockUser)
    
    console.log('🧪 Test result:', result)
    
    if (result && result.length > 0) {
      const appointment = result[0]
      console.log('✅ Auto-scheduling test PASSED - appointment created:', {
        id: appointment.id,
        date: appointment.date,
        time: appointment.time,
        serviceName: appointment.serviceNames[0],
        doctorId: appointment.doctorId,
        status: appointment.status
      })
    } else {
      console.log('❌ Auto-scheduling test FAILED - no appointment created')
    }
    
    return result
  } catch (error) {
    console.error('❌ Auto-scheduling test ERROR:', error)
    return null
  }
}

/**
 * Debug function to check why auto-scheduled appointments might not be showing
 * This can be called from browser console for debugging
 */
export async function debugAutoScheduledAppointments() {
  try {
    console.log('🔍 Debugging auto-scheduled appointments...')
    
    // Get current vet ID from auth store
    const { useAuthStore } = await import('@/stores/modules/authStore')
    const authStore = useAuthStore()
    const currentVetId = authStore.user?.userId
    
    console.log('👨‍⚕️ Current vet ID:', currentVetId)
    
    if (!currentVetId) {
      console.log('❌ No vet ID found in auth store')
      return
    }
    
    // Query for auto-scheduled appointments for this vet
    const appointmentsRef = collection(db, 'appointments')
    const q = query(
      appointmentsRef,
      where('doctorId', '==', currentVetId),
      where('isAutoScheduled', '==', true),
      where('status', '==', 'approved')
    )
    
    const querySnapshot = await getDocs(q)
    const autoScheduledAppointments = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
    
    console.log('🔍 Found auto-scheduled appointments:', autoScheduledAppointments.length)
    console.log('🔍 Auto-scheduled appointments:', autoScheduledAppointments.map(apt => ({
      id: apt.id,
      date: apt.date,
      time: apt.time,
      serviceNames: apt.serviceNames,
      doctorId: apt.doctorId,
      status: apt.status,
      createdAt: apt.createdAt
    })))
    
    // Also check all approved appointments for this vet
    const allApprovedQuery = query(
      appointmentsRef,
      where('doctorId', '==', currentVetId),
      where('status', '==', 'approved')
    )
    
    const allApprovedSnapshot = await getDocs(allApprovedQuery)
    const allApprovedAppointments = allApprovedSnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
    
    console.log('🔍 All approved appointments for this vet:', allApprovedAppointments.length)
    console.log('🔍 All approved appointments:', allApprovedAppointments.map(apt => ({
      id: apt.id,
      date: apt.date,
      time: apt.time,
      serviceNames: apt.serviceNames,
      doctorId: apt.doctorId,
      isAutoScheduled: apt.isAutoScheduled,
      createdAt: apt.createdAt
    })))
    
    // Check for any appointments with the current vet's name (fallback)
    const vetNameQuery = query(
      appointmentsRef,
      where('doctorName', '==', authStore.user?.firstName || authStore.user?.name)
    )
    
    const vetNameSnapshot = await getDocs(vetNameQuery)
    const vetNameAppointments = vetNameSnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
    
    console.log('🔍 Appointments with vet name:', vetNameAppointments.length)
    console.log('🔍 Vet name appointments:', vetNameAppointments.map(apt => ({
      id: apt.id,
      date: apt.date,
      time: apt.time,
      serviceNames: apt.serviceNames,
      doctorId: apt.doctorId,
      doctorName: apt.doctorName,
      isAutoScheduled: apt.isAutoScheduled,
      status: apt.status
    })))
    
    return {
      autoScheduled: autoScheduledAppointments,
      allApproved: allApprovedAppointments,
      vetNameAppointments: vetNameAppointments
    }
    
  } catch (error) {
    console.error('❌ Error debugging auto-scheduled appointments:', error)
    return null
  }
}

/**
 * Create a vaccination appointment from suggestion
 * @param {Object} suggestion - Vaccination suggestion
 * @param {Object} user - User object
 * @param {Object} pet - Pet object
 * @returns {Promise<Object>} Created appointment
 */
export async function createVaccinationAppointment(suggestion, user, pet) {
  try {
    console.log('🩺 Creating vaccination appointment from suggestion:', suggestion)
    
    // Calculate next vaccination date based on vaccine type
    const nextVaccinationDate = calculateNextVaccinationDate(suggestion.serviceName, new Date())
    
    // Create appointment data
    const appointmentData = {
      userId: user?.id || user?.userId,
      petIds: [pet.id],
      petNames: [pet.name],
      servicesIds: [suggestion.serviceId],
      serviceNames: [suggestion.serviceName],
      date: nextVaccinationDate,
      time: suggestion.time || '9:00 AM', // Default time
      duration: suggestion.estimatedDuration || 30,
      status: 'approved', // Auto-approved
      doctorId: null, // Will be assigned later
      doctorName: null,
      isVaccination: true,
      isAutoScheduled: true,
      autoScheduledAt: new Date(),
      autoScheduledReason: 'Vaccination series continuation',
      vaccinationSeries: suggestion.series,
      vaccinationDose: suggestion.dose,
      vaccinationTotalDoses: suggestion.totalDoses,
      isCore: suggestion.isCore,
      notes: `Auto-scheduled vaccination: ${suggestion.description}`,
      createdAt: new Date(),
      updatedAt: new Date(),
      source: 'vaccination_auto_schedule',
      originalSuggestionId: suggestion.id
    }
    
    // Save to appointments collection
    const appointmentRef = doc(collection(db, 'appointments'))
    await setDoc(appointmentRef, {
      ...appointmentData,
      id: appointmentRef.id
    })
    
    console.log('✅ Created vaccination appointment:', appointmentRef.id)
    
    // Update suggestion status to converted
    await updateVaccinationSuggestionStatus(suggestion.id, 'converted')
    
    return { ...appointmentData, id: appointmentRef.id }
  } catch (error) {
    console.error('Error creating vaccination appointment:', error)
    throw new Error('Failed to create vaccination appointment')
  }
}

/**
 * Test function to verify booster limit functionality
 * @param {Object} mockVaccinationService - Mock vaccination service with totalBoosters
 * @param {Object} mockPet - Mock pet object
 * @param {Array} mockExistingVaccinations - Mock existing vaccination records
 * @returns {Promise<Object>} Test results
 */
export async function testBoosterLimitFunctionality(mockVaccinationService, mockPet, mockExistingVaccinations = []) {
  try {
    console.log('🧪 Testing booster limit functionality...')
    
    const testResults = {
      service: mockVaccinationService,
      pet: mockPet,
      existingVaccinations: mockExistingVaccinations,
      tests: []
    }
    
    // Test 1: First vaccination (should allow scheduling)
    const firstVaccination = {
      name: mockVaccinationService.name,
      serviceId: mockVaccinationService.id,
      doctorId: 'test_vet',
      doctorName: 'Test Vet',
      appointmentTime: '1:00 PM - 2:00 PM',
      appointmentDuration: 60,
      isCore: true
    }
    
    const firstTest = await checkBoosterLimits(firstVaccination, mockPet, mockVaccinationService)
    testResults.tests.push({
      test: 'First vaccination',
      shouldSchedule: firstTest.shouldSchedule,
      reason: firstTest.reason,
      currentBoosters: firstTest.currentBoosters,
      totalBoosters: firstTest.totalBoosters,
      nextBoosterNumber: firstTest.nextBoosterNumber
    })
    
    // Test 2: After reaching limit (should not allow scheduling)
    const limitReachedVaccination = {
      name: `${mockVaccinationService.name} - BOOSTER ${mockVaccinationService.totalBoosters}`,
      serviceId: mockVaccinationService.id,
      doctorId: 'test_vet',
      doctorName: 'Test Vet',
      appointmentTime: '1:00 PM - 2:00 PM',
      appointmentDuration: 60,
      isCore: true
    }
    
    // Mock existing vaccinations to simulate limit reached
    const mockPetWithVaccinations = {
      ...mockPet,
      vaccinations: mockExistingVaccinations
    }
    
    const limitTest = await checkBoosterLimits(limitReachedVaccination, mockPetWithVaccinations, mockVaccinationService)
    testResults.tests.push({
      test: 'After reaching limit',
      shouldSchedule: limitTest.shouldSchedule,
      reason: limitTest.reason,
      currentBoosters: limitTest.currentBoosters,
      totalBoosters: limitTest.totalBoosters,
      nextBoosterNumber: limitTest.nextBoosterNumber
    })
    
    // Test 3: Booster schedule calculation
    const boosterScheduleTest = calculateNextVaccinationDateFromBoosterSchedule(
      mockVaccinationService, 
      firstTest, 
      new Date()
    )
    
    testResults.tests.push({
      test: 'Booster schedule calculation',
      nextDate: boosterScheduleTest,
      hasBoosterSchedule: !!(mockVaccinationService.boosterSchedule && Object.keys(mockVaccinationService.boosterSchedule).length > 0)
    })
    
    console.log('🧪 Test results:', testResults)
    return testResults
    
  } catch (error) {
    console.error('Error testing booster limit functionality:', error)
    return {
      error: error.message,
      service: mockVaccinationService,
      pet: mockPet
    }
  }
}

/**
 * Calculate next vaccination date based on vaccine type
 * @param {string} vaccineName - Name of the vaccine
 * @param {Date} currentDate - Current date
 * @returns {Date} Next vaccination date
 */
function calculateNextVaccinationDate(vaccineName, currentDate) {
  const vaccineNameLower = vaccineName.toLowerCase()
  const nextDate = new Date(currentDate)
  
  // Common vaccine schedules
  if (vaccineNameLower.includes('rabies')) {
    nextDate.setFullYear(nextDate.getFullYear() + 1) // 1 year
  } else if (vaccineNameLower.includes('dhpp') || vaccineNameLower.includes('dhp')) {
    nextDate.setFullYear(nextDate.getFullYear() + 1) // 1 year
  } else if (vaccineNameLower.includes('bordetella')) {
    nextDate.setMonth(nextDate.getMonth() + 6) // 6 months
  } else if (vaccineNameLower.includes('feline') || vaccineNameLower.includes('fiv')) {
    nextDate.setFullYear(nextDate.getFullYear() + 1) // 1 year
  } else {
    // Default to 1 year for unknown vaccines
    nextDate.setFullYear(nextDate.getFullYear() + 1)
  }
  
  return nextDate
}

/**
 * Calculate next vaccination date using service configuration and office hours
 * @param {Object} vaccinationService - Vaccination service object
 * @param {Date} currentDate - Current date
 * @param {string} userId - User ID to check for conflicts
 * @param {string} petId - Pet ID to check for conflicts
 * @returns {Promise<Date>} Next vaccination date that falls on an open day
 */
async function calculateNextVaccinationDateFromService(vaccinationService, currentDate, userId, petId) {
  const nextDate = new Date(currentDate)
  
  if (!vaccinationService.nextDoseIn || !vaccinationService.nextDoseUnit) {
    console.log('⚠️ No nextDoseIn or nextDoseUnit found, using default 1 year')
    nextDate.setFullYear(nextDate.getFullYear() + 1)
    return await adjustDateToOfficeHours(nextDate, userId, petId)
  }
  
  const doseValue = parseInt(vaccinationService.nextDoseIn)
  const doseUnit = vaccinationService.nextDoseUnit.toLowerCase()
  
  console.log('🔍 Calculating next dose date:', {
    doseValue,
    doseUnit,
    currentDate: currentDate.toISOString(),
    userId,
    petId
  })
  
  switch (doseUnit) {
    case 'days':
      nextDate.setDate(nextDate.getDate() + doseValue)
      break
    case 'weeks':
      nextDate.setDate(nextDate.getDate() + (doseValue * 7))
      break
    case 'months':
      nextDate.setMonth(nextDate.getMonth() + doseValue)
      break
    case 'years':
      nextDate.setFullYear(nextDate.getFullYear() + doseValue)
      break
    default:
      console.log('⚠️ Unknown dose unit, using default 1 year')
      nextDate.setFullYear(nextDate.getFullYear() + 1)
  }
  
  console.log('✅ Calculated initial next vaccination date:', nextDate.toISOString())
  
  // Adjust the date to fall on an open day
  const adjustedDate = await adjustDateToOfficeHours(nextDate, userId, petId)
  console.log('✅ Adjusted to office hours:', adjustedDate.toISOString())
  
  return adjustedDate
}

/**
 * Adjust date to fall on an open day and during business hours
 * @param {Date} targetDate - The target date to adjust
 * @param {string} userId - User ID to check for existing appointments
 * @param {string} petId - Pet ID to check for existing appointments
 * @returns {Promise<Date>} Adjusted date that falls on an open day with no conflicts
 */
async function adjustDateToOfficeHours(targetDate, userId, petId) {
  try {
    console.log('🏢 Adjusting date to office hours for:', targetDate.toISOString())
    console.log('🏢 Checking for conflicts for user:', userId, 'pet:', petId)
    
    // Get office hours from Firestore
    const officeHours = await getOfficeHours()
    console.log('🏢 Office hours loaded:', officeHours)
    
    let adjustedDate = new Date(targetDate)
    let attempts = 0
    const maxAttempts = 60 // Increased to allow more attempts for conflict resolution
    
    while (attempts < maxAttempts) {
      const dayName = getDayName(adjustedDate)
      const dayHours = officeHours[dayName]
      
      console.log(`🏢 Checking ${dayName}:`, dayHours)
      
      if (dayHours && dayHours.isOpen) {
        // Check for existing appointments on this date
        const hasConflict = await checkForAppointmentConflict(adjustedDate, userId, petId)
        
        if (!hasConflict) {
          // Set the time to a reasonable business hour (9:00 AM)
          adjustedDate.setHours(9, 0, 0, 0)
          console.log(`✅ Found available day: ${dayName} at ${adjustedDate.toISOString()}`)
          return adjustedDate
        } else {
          console.log(`⚠️ Conflict found on ${dayName}, moving to next day`)
        }
      } else {
        console.log(`🏢 ${dayName} is closed, moving to next day`)
      }
      
      // Move to next day
      adjustedDate.setDate(adjustedDate.getDate() + 1)
      attempts++
      console.log(`🏢 Attempt ${attempts} of ${maxAttempts}`)
    }
    
    console.log('⚠️ Could not find available day within 60 attempts, using original date')
    return targetDate
    
  } catch (error) {
    console.error('Error adjusting date to office hours:', error)
    return targetDate // Return original date if there's an error
  }
}

/**
 * Check for existing appointments on a specific date for a user/pet
 * @param {Date} date - Date to check
 * @param {string} userId - User ID
 * @param {string} petId - Pet ID
 * @returns {Promise<boolean>} True if there's a conflict
 */
async function checkForAppointmentConflict(date, userId, petId) {
  try {
    if (!userId || !petId) {
      console.log('⚠️ No userId or petId provided, skipping conflict check')
      return false
    }
    
    // Create date range for the specific day
    const startOfDay = new Date(date)
    startOfDay.setHours(0, 0, 0, 0)
    
    const endOfDay = new Date(date)
    endOfDay.setHours(23, 59, 59, 999)
    
    console.log('🔍 Checking for conflicts on:', date.toISOString())
    console.log('🔍 Date range:', startOfDay.toISOString(), 'to', endOfDay.toISOString())
    
    // Query for existing appointments
    const appointmentsRef = collection(db, 'appointments')
    const q = query(
      appointmentsRef,
      where('userId', '==', userId),
      where('petIds', 'array-contains', petId),
      where('date', '>=', startOfDay),
      where('date', '<=', endOfDay),
      where('status', 'in', ['pending', 'approved', 'in-progress'])
    )
    
    const querySnapshot = await getDocs(q)
    const existingAppointments = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
    
    console.log('🔍 Found existing appointments:', existingAppointments.length)
    
    if (existingAppointments.length > 0) {
      console.log('⚠️ Conflicts found:', existingAppointments.map(apt => ({
        id: apt.id,
        date: apt.date,
        time: apt.time,
        status: apt.status,
        serviceNames: apt.serviceNames
      })))
      return true
    }
    
    console.log('✅ No conflicts found for this date')
    return false
    
  } catch (error) {
    console.error('Error checking for appointment conflicts:', error)
    return false // Assume no conflict if there's an error
  }
}

/**
 * Get office hours from Firestore
 * @returns {Promise<Object>} Office hours by day
 */
async function getOfficeHours() {
  try {
    const officeHoursRef = collection(db, 'officeHours')
    const snapshot = await getDocs(officeHoursRef)
    
    const officeHours = {}
    snapshot.forEach(doc => {
      const data = doc.data()
      officeHours[data.day] = {
        isOpen: data.isOpen,
        openTime: data.openTime,
        closeTime: data.closeTime,
        lunchStart: data.lunchStart,
        lunchEnd: data.lunchEnd
      }
    })
    
    console.log('🏢 Office hours fetched:', officeHours)
    return officeHours
    
  } catch (error) {
    console.error('Error fetching office hours:', error)
    // Return default office hours (Mon-Fri 9-5) if fetch fails
    return {
      'Monday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Tuesday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Wednesday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Thursday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Friday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Saturday': { isOpen: true, openTime: '08:00', closeTime: '17:00' },
      'Sunday': { isOpen: false }
    }
  }
}

/**
 * Get day name from date
 * @param {Date} date - Date object
 * @returns {string} Day name
 */
function getDayName(date) {
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  return days[date.getDay()]
}

// Removed getBestAvailableTimeSlot function - no longer needed since we use original appointment time

// Removed parseTimeString and formatTimeString functions - no longer needed

/**
 * Send notification to user and vet about scheduled vaccination appointment
 * @param {Object} appointment - Created appointment
 * @param {Object} pet - Pet object
 * @param {Object} user - User object
 * @returns {Promise} Notification result
 */
export async function sendVaccinationAppointmentNotification(appointment, pet, user) {
  try {
    console.log('📧 Sending vaccination appointment notifications...')
    
    // Send notification to user
    const userNotificationData = {
      userId: user?.id || user?.userId,
      type: 'vaccination_scheduled',
      title: 'Vaccination Appointment Scheduled',
      message: `A vaccination appointment for ${pet.name} has been automatically scheduled for ${formatDate(appointment.date)} at ${appointment.time}.`,
      data: {
        appointmentId: appointment.id,
        petId: pet.id,
        petName: pet.name,
        serviceName: appointment.serviceNames[0],
        scheduledDate: appointment.date,
        scheduledTime: appointment.time,
        isAutoScheduled: true
      },
      priority: 'medium',
      read: false,
      createdAt: new Date()
    }
    
    const userNotificationId = await createNotification(userNotificationData)
    console.log('✅ User vaccination appointment notification sent:', userNotificationId)
    
    // Send notification to vet (doctor)
    if (appointment.doctorId && appointment.doctorId !== 'auto-scheduled') {
      const vetNotificationData = {
        userId: appointment.doctorId,
        type: 'vaccination_auto_scheduled',
        title: 'Auto-Scheduled Vaccination Appointment',
        message: `A vaccination appointment for ${pet.name} (${pet.species}) has been automatically scheduled for ${formatDate(appointment.date)} at ${appointment.time}.`,
        data: {
          appointmentId: appointment.id,
          petId: pet.id,
          petName: pet.name,
          petSpecies: pet.species,
          serviceName: appointment.serviceNames[0],
          scheduledDate: appointment.date,
          scheduledTime: appointment.time,
          isAutoScheduled: true,
          ownerName: user?.firstName ? `${user.firstName} ${user.lastName || ''}`.trim() : 'Pet Owner'
        },
        priority: 'medium',
        read: false,
        createdAt: new Date()
      }
      
      const vetNotificationId = await createNotification(vetNotificationData)
      console.log('✅ Vet vaccination appointment notification sent:', vetNotificationId)
    } else {
      console.log('ℹ️ No vet notification sent - doctorId is auto-scheduled or missing')
    }
    
    return userNotificationId
  } catch (error) {
    console.error('Error sending vaccination appointment notifications:', error)
    // Don't throw error - notification failure shouldn't break the appointment creation
    return false
  }
}

/**
 * Format date for notification message
 * @param {Date} date - Date to format
 * @returns {string} Formatted date string
 */
function formatDate(date) {
  if (!date) return 'Unknown date'
  
  const dateObj = date instanceof Date ? date : new Date(date)
  return dateObj.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
