// services/vaccinationService.js
import { doc, updateDoc, arrayUnion, arrayRemove, getDoc, collection, query, where, getDocs } from 'firebase/firestore'
import { db } from '@shared/firebase'
import { processCompletedVaccination } from './vaccinationAutoScheduler'

/**
 * Automatically generate vaccination records from completed vaccination appointments
 * @param {Object} appointment - The completed appointment object
 * @param {Object} pet - The pet object
 * @param {Array} serviceDetails - Array of service objects with full details
 * @returns {Object} Generated vaccination record
 */
export function generateVaccinationRecord(appointment, pet, serviceDetails) {
  // Find vaccination service from the service details
  const vaccinationService = serviceDetails?.find(service => 
    service.isVaccination === true || 
    service.name?.toLowerCase().includes('vaccination') ||
    service.name?.toLowerCase().includes('vaccine') ||
    service.name?.toLowerCase().includes('shot')
  )

  if (!vaccinationService) {
    return null
  }

  // Calculate default dates based on vaccine type
  const { expiryDate, nextDueDate } = calculateVaccineDates(
    vaccinationService.name,
    appointment.completedAt || appointment.date
  )

  // Generate vaccination record
  const vaccinationRecord = {
    id: `vacc_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    name: vaccinationService.name,
    date: appointment.completedAt || appointment.date,
    expiryDate: expiryDate,
    nextDueDate: nextDueDate,
    completed: true,
    batchNumber: vaccinationService.batchNumber || generateBatchNumber(),
    administeredBy: appointment.doctorName || 'Unknown',
    doctorId: appointment.doctorId || appointment.completedBy || appointment.administeredBy, // Enhanced doctor ID capture
    doctorName: appointment.doctorName || appointment.administeredBy || 'Unknown',
    location: appointment.location || 'Veterinary Clinic',
    description: vaccinationService.description || 'Vaccination administered during appointment',
    notes: appointment.completionData?.generalNotes?.treatmentSummary || '',
    appointmentId: appointment.id,
    serviceId: vaccinationService.id,
    // Store appointment time and duration for auto-scheduling
    appointmentTime: appointment.time || '1:00 PM - 2:00 PM',
    appointmentDuration: appointment.duration || 60,
    // Store vaccination service data for auto-scheduling
    vaccinationServiceData: {
      id: vaccinationService.id,
      name: vaccinationService.name,
      nextDoseIn: vaccinationService.nextDoseIn,
      nextDoseUnit: vaccinationService.nextDoseUnit,
      autoSchedule: vaccinationService.autoSchedule,
      seriesType: vaccinationService.seriesType,
      totalBoosters: vaccinationService.totalBoosters,
      vaccineType: vaccinationService.vaccineType
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    isAutoGenerated: true, // Flag to identify auto-generated records
    source: 'appointment'
  }

  // 🔧 DEBUG: Log the doctor ID being captured
  console.log('🔍 Vaccination record doctor ID capture:', {
    appointmentDoctorId: appointment.doctorId,
    appointmentCompletedBy: appointment.completedBy,
    appointmentAdministeredBy: appointment.administeredBy,
    finalDoctorId: vaccinationRecord.doctorId,
    finalDoctorName: vaccinationRecord.doctorName
  })

  return vaccinationRecord
}

/**
 * Enhanced vaccination record generation with autoscheduling
 * @param {Object} appointment - The completed appointment object
 * @param {Object} pet - The pet object
 * @param {Array} serviceDetails - Array of service objects with full details
 * @param {Object} user - User object (owner)
 * @returns {Promise<Object>} Generated vaccination record and new suggestions
 */
export async function generateVaccinationRecordWithAutoScheduling(appointment, pet, serviceDetails, user = null) {
  // Generate the basic vaccination record
  const vaccinationRecord = generateVaccinationRecord(appointment, pet, serviceDetails)
  
  if (!vaccinationRecord) {
    return { vaccinationRecord: null, newSuggestions: [], autoScheduled: false }
  }
  
  try {
    console.log('🩺 Processing vaccination record for auto-scheduling:', vaccinationRecord.name)
    
    // Process the completed vaccination and auto-schedule next doses
    const newSuggestions = await processCompletedVaccination(vaccinationRecord, pet, user)
    
    console.log('🩺 Auto-scheduling result:', {
      vaccinationRecord: vaccinationRecord.name,
      newSuggestions: newSuggestions.length,
      autoScheduled: newSuggestions.length > 0
    })
    
    return {
      vaccinationRecord,
      newSuggestions,
      autoScheduled: newSuggestions.length > 0
    }
  } catch (error) {
    console.error('Error in auto-scheduling vaccinations:', error)
    // Return the vaccination record even if autoscheduling fails
    return {
      vaccinationRecord,
      newSuggestions: [],
      autoScheduled: false,
      error: error.message
    }
  }
}

/**
 * Calculate vaccine expiry and next due dates based on vaccine type
 * @param {string} vaccineName - Name of the vaccine
 * @param {Date} adminDate - Date vaccine was administered
 * @returns {Object} Object with expiryDate and nextDueDate
 */
function calculateVaccineDates(vaccineName, adminDate) {
  const adminDateObj = new Date(adminDate)
  const vaccineNameLower = vaccineName.toLowerCase()
  
  let expiryDate = null
  let nextDueDate = null

  // Common vaccine schedules (in months)
  if (vaccineNameLower.includes('rabies')) {
    expiryDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
    nextDueDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
  } else if (vaccineNameLower.includes('dhpp') || vaccineNameLower.includes('dhp')) {
    expiryDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
    nextDueDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
  } else if (vaccineNameLower.includes('bordetella')) {
    expiryDate = new Date(adminDateObj.getTime() + (6 * 30 * 24 * 60 * 60 * 1000)) // 6 months
    nextDueDate = new Date(adminDateObj.getTime() + (6 * 30 * 24 * 60 * 60 * 1000)) // 6 months
  } else if (vaccineNameLower.includes('feline') || vaccineNameLower.includes('fiv')) {
    expiryDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
    nextDueDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000)) // 1 year
  } else {
    // Default to 1 year for unknown vaccines
    expiryDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000))
    nextDueDate = new Date(adminDateObj.getTime() + (365 * 24 * 60 * 60 * 1000))
  }

  return { expiryDate, nextDueDate }
}

/**
 * Generate a batch number for vaccination records
 * @returns {string} Generated batch number
 */
function generateBatchNumber() {
  const date = new Date()
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  const random = Math.random().toString(36).substr(2, 6).toUpperCase()
  
  return `BATCH-${year}${month}${day}-${random}`
}

/**
 * Add vaccination record to pet's vaccinations array
 * @param {string} petId - Pet ID
 * @param {Object} vaccinationRecord - Vaccination record to add
 * @returns {Promise} Update result
 */
export async function addVaccinationToPet(petId, vaccinationRecord) {
  try {
    // Get the pet document reference
    const petRef = doc(db, 'pets', petId)
    
    // Update the pet document to add the vaccination
    await updateDoc(petRef, {
      vaccinations: arrayUnion(vaccinationRecord),
      updatedAt: new Date()
    })

    return { success: true, message: 'Vaccination record added successfully' }
  } catch (error) {
    console.error('Error adding vaccination to pet:', error)
    throw new Error('Failed to add vaccination record to pet')
  }
}

/**
 * Update existing vaccination record
 * @param {string} petId - Pet ID
 * @param {string} vaccinationId - Vaccination record ID
 * @param {Object} updatedData - Updated vaccination data
 * @returns {Promise} Update result
 */
export async function updateVaccinationRecord(petId, vaccinationId, updatedData) {
  try {
    // Get the pet document
    const petRef = doc(db, 'pets', petId)
    const petDoc = await getDoc(petRef)
    
    if (!petDoc.exists()) {
      throw new Error('Pet not found')
    }

    const petData = petDoc.data()
    const vaccinations = petData.vaccinations || []
    
    // Find and update the vaccination record
    const updatedVaccinations = vaccinations.map(vaccination => {
      if (vaccination.id === vaccinationId) {
        return {
          ...vaccination,
          ...updatedData,
          updatedAt: new Date(),
          isAutoGenerated: false, // Mark as manually edited
          source: 'manual'
        }
      }
      return vaccination
    })

    // Update the pet document
    await updateDoc(petRef, {
      vaccinations: updatedVaccinations,
      updatedAt: new Date()
    })

    return { success: true, message: 'Vaccination record updated successfully' }
  } catch (error) {
    console.error('Error updating vaccination record:', error)
    throw new Error('Failed to update vaccination record')
  }
}

/**
 * Remove vaccination record from pet
 * @param {string} petId - Pet ID
 * @param {string} vaccinationId - Vaccination record ID
 * @returns {Promise} Update result
 */
export async function removeVaccinationRecord(petId, vaccinationId) {
  try {
    // Get the pet document
    const petRef = doc(db, 'pets', petId)
    const petDoc = await getDoc(petRef)
    
    if (!petDoc.exists()) {
      throw new Error('Pet not found')
    }

    const petData = petDoc.data()
    const vaccinations = petData.vaccinations || []
    
    // Find the vaccination record to remove
    const vaccinationToRemove = vaccinations.find(v => v.id === vaccinationId)
    if (!vaccinationToRemove) {
      throw new Error('Vaccination record not found')
    }

    // Remove the vaccination record
    const updatedVaccinations = vaccinations.filter(v => v.id !== vaccinationId)
    
    // Update the pet document
    await updateDoc(petRef, {
      vaccinations: updatedVaccinations,
      updatedAt: new Date()
    })

    return { success: true, message: 'Vaccination record removed successfully' }
  } catch (error) {
    console.error('Error removing vaccination record:', error)
    throw new Error('Failed to remove vaccination record')
  }
}

/**
 * Check if appointment should generate vaccination record
 * @param {Object} appointment - Appointment object
 * @param {Array} serviceDetails - Array of service objects with full details
 * @returns {boolean} True if appointment should generate vaccination record
 */
export function shouldGenerateVaccinationRecord(appointment, serviceDetails) {
  // Check if appointment is completed
  if (appointment.status !== 'completed') {
    return false
  }

  // Check if any service is a vaccination by looking at service details
  const hasVaccinationService = serviceDetails?.some(service => 
    service.isVaccination === true ||
    service.name?.toLowerCase().includes('vaccination') ||
    service.name?.toLowerCase().includes('vaccine') ||
    service.name?.toLowerCase().includes('shot')
  )

  return hasVaccinationService
}

/**
 * Get all vaccination records for a pet
 * @param {Object} pet - Pet object
 * @returns {Array} Array of vaccination records
 */
export function getPetVaccinations(pet) {
  return pet.vaccinations || []
}

/**
 * Fetch service details by service IDs
 * @param {Array} serviceIds - Array of service IDs
 * @returns {Promise<Array>} Array of service objects
 */
export async function fetchServiceDetails(serviceIds) {
  try {
    if (!serviceIds || serviceIds.length === 0) {
      return []
    }

    const servicesRef = collection(db, 'services')
    const serviceDetails = []

    for (const serviceId of serviceIds) {
      try {
        const serviceDoc = await getDoc(doc(db, 'services', serviceId))
        if (serviceDoc.exists()) {
          const serviceData = serviceDoc.data()
          serviceDetails.push({
            id: serviceDoc.id,
            ...serviceData
          })
        }
      } catch (error) {
        console.error(`Error fetching service ${serviceId}:`, error)
      }
    }

    return serviceDetails
  } catch (error) {
    console.error('Error fetching service details:', error)
    return []
  }
}

/**
 * Merge appointment-based and manual vaccination records
 * @param {Array} appointmentVaccinations - Vaccinations from appointments
 * @param {Array} manualVaccinations - Manually added vaccinations
 * @returns {Array} Merged and deduplicated vaccination records
 */
export function mergeVaccinationRecords(appointmentVaccinations, manualVaccinations) {
  const allVaccinations = [...(appointmentVaccinations || []), ...(manualVaccinations || [])]
  
  // Remove duplicates based on appointmentId and serviceId
  const uniqueVaccinations = allVaccinations.filter((vaccination, index, self) => {
    if (vaccination.appointmentId && vaccination.serviceId) {
      return index === self.findIndex(v => 
        v.appointmentId === vaccination.appointmentId && 
        v.serviceId === vaccination.serviceId
      )
    }
    return true
  })

  // Sort by date (newest first)
  return uniqueVaccinations.sort((a, b) => new Date(b.date) - new Date(a.date))
}
