<!-- components/common/VaccinationForm.vue -->
<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded-xl shadow-xl max-w-2xl w-full mx-auto max-h-[90vh] overflow-y-auto">
      <!-- Header -->
      <div class="flex items-center justify-between p-6 border-b border-gray-200">
        <h2 class="text-xl font-semibold text-gray-900">
          {{ isEditing ? 'Edit Vaccination' : 'Add New Vaccination' }}
        </h2>
        <button 
          @click="$emit('close')"
          class="text-gray-400 hover:text-gray-600 transition-colors"
        >
          <XIcon class="w-6 h-6" />
        </button>
      </div>

      <!-- Form -->
      <form @submit.prevent="handleSubmit" class="p-6 space-y-6">
                 <!-- Pet Info Display -->
         <div class="bg-gray-50 rounded-lg p-4">
           <div class="flex items-center gap-3">
             <div class="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center">
               <SyringeIcon class="w-6 h-6 text-blue-600" />
             </div>
             <div>
               <h3 class="font-medium text-gray-900">{{ pet.name }}</h3>
               <p class="text-sm text-gray-600">{{ pet.breed }} • {{ pet.species }}</p>
               <div v-if="vaccination?.isAutoGenerated" class="mt-2">
                 <span class="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded-full">
                   Auto-generated from appointment
                 </span>
               </div>
             </div>
           </div>
         </div>

        <!-- Vaccination Details -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <!-- Vaccination Name -->
          <div class="md:col-span-2">
            <label for="name" class="block text-sm font-medium text-gray-700 mb-2">
              Vaccination Name <span class="text-red-500">*</span>
            </label>
            <input
              id="name"
              v-model="form.name"
              type="text"
              required
              placeholder="e.g., Rabies Vaccine, DHPP, Bordetella"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Date Administered -->
          <div>
            <label for="date" class="block text-sm font-medium text-gray-700 mb-2">
              Date Administered <span class="text-red-500">*</span>
            </label>
            <input
              id="date"
              v-model="form.date"
              type="date"
              required
              :max="new Date().toISOString().split('T')[0]"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Expiry Date -->
          <div>
            <label for="expiryDate" class="block text-sm font-medium text-gray-700 mb-2">
              Expiry Date
            </label>
            <input
              id="expiryDate"
              v-model="form.expiryDate"
              type="date"
              :min="form.date"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Next Due Date -->
          <div>
            <label for="nextDueDate" class="block text-sm font-medium text-gray-700 mb-2">
              Next Due Date
            </label>
            <input
              id="nextDueDate"
              v-model="form.nextDueDate"
              type="date"
              :min="form.date"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Status -->
          <div>
            <label for="status" class="block text-sm font-medium text-gray-700 mb-2">
              Status
            </label>
            <select
              id="status"
              v-model="form.completed"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            >
              <option :value="true">Completed</option>
              <option :value="false">Scheduled</option>
            </select>
          </div>

          <!-- Batch Number -->
          <div>
            <label for="batchNumber" class="block text-sm font-medium text-gray-700 mb-2">
              Batch Number
            </label>
            <input
              id="batchNumber"
              v-model="form.batchNumber"
              type="text"
              placeholder="e.g., BATCH-2024-001"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Administered By -->
          <div>
            <label for="administeredBy" class="block text-sm font-medium text-gray-700 mb-2">
              Administered By
            </label>
            <input
              id="administeredBy"
              v-model="form.administeredBy"
              type="text"
              placeholder="Veterinarian name"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Location -->
          <div>
            <label for="location" class="block text-sm font-medium text-gray-700 mb-2">
              Location
            </label>
            <input
              id="location"
              v-model="form.location"
              type="text"
              placeholder="Clinic name or location"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
          </div>

          <!-- Description -->
          <div class="md:col-span-2">
            <label for="description" class="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              id="description"
              v-model="form.description"
              rows="3"
              placeholder="Additional details about the vaccination"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            ></textarea>
          </div>

          <!-- Notes -->
          <div class="md:col-span-2">
            <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
              Notes
            </label>
            <textarea
              id="notes"
              v-model="form.notes"
              rows="3"
              placeholder="Any special notes or observations"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            ></textarea>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex justify-end gap-3 pt-4 border-t border-gray-200">
          <button
            type="button"
            @click="$emit('close')"
            class="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            :disabled="isSubmitting"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            <LoadingSpinner v-if="isSubmitting" class="w-4 h-4" />
            {{ isEditing ? 'Update Vaccination' : 'Add Vaccination' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { XIcon, SyringeIcon } from 'lucide-vue-next'
import LoadingSpinner from './LoadingSpinner.vue'

const props = defineProps({
  pet: {
    type: Object,
    required: true
  },
  vaccination: {
    type: Object,
    default: null
  },
  isEditing: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['close', 'save'])

const isSubmitting = ref(false)

// Form data
const form = ref({
  name: '',
  date: '',
  expiryDate: '',
  nextDueDate: '',
  completed: true,
  batchNumber: '',
  administeredBy: '',
  location: '',
  description: '',
  notes: ''
})

// Initialize form with existing data if editing
onMounted(() => {
  if (props.isEditing && props.vaccination) {
    form.value = {
      name: props.vaccination.name || '',
      date: props.vaccination.date ? new Date(props.vaccination.date).toISOString().split('T')[0] : '',
      expiryDate: props.vaccination.expiryDate ? new Date(props.vaccination.expiryDate).toISOString().split('T')[0] : '',
      nextDueDate: props.vaccination.nextDueDate ? new Date(props.vaccination.nextDueDate).toISOString().split('T')[0] : '',
      completed: props.vaccination.completed !== undefined ? props.vaccination.completed : true,
      batchNumber: props.vaccination.batchNumber || '',
      administeredBy: props.vaccination.administeredBy || '',
      location: props.vaccination.location || '',
      description: props.vaccination.description || '',
      notes: props.vaccination.notes || ''
    }
  } else {
    // Set default date to today
    form.value.date = new Date().toISOString().split('T')[0]
  }
})

const handleSubmit = async () => {
  try {
    isSubmitting.value = true
    
    // Validate form
    if (!form.value.name || !form.value.date) {
      alert('Please fill in all required fields')
      return
    }

    // Prepare vaccination data
    const vaccinationData = {
      ...form.value,
      date: new Date(form.value.date),
      expiryDate: form.value.expiryDate ? new Date(form.value.expiryDate) : null,
      nextDueDate: form.value.nextDueDate ? new Date(form.value.nextDueDate) : null,
      createdAt: props.isEditing ? props.vaccination.createdAt : new Date(),
      updatedAt: new Date()
    }

    // Emit save event
    emit('save', vaccinationData)
    
  } catch (error) {
    console.error('Error saving vaccination:', error)
    alert('Error saving vaccination. Please try again.')
  } finally {
    isSubmitting.value = false
  }
}
</script>

<style scoped>
/* Custom scrollbar for the modal */
.overflow-y-auto::-webkit-scrollbar {
  width: 6px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 3px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: #c1c1c1;
  border-radius: 3px;
}

.overflow-y-auto::-webkit-scrollbar-thumb:hover {
  background: #a8a8a8;
}
</style>
